### ISSUE TITLE
Could provide windows version

### ISSUE THREAD

**Issue by cheery550** [aheit/cantools#1]
could the author provided the version of windows?

**Comment by aheit** [comment]
Hello Cheery,

> could the author provided the version of windows?

Do you mean the version I am using? I have Windows 10, 64 Bit.

But if you are asking me to provide windows binaries of cantools, I have to
apologize, I cannot do that. The effort for me is too high to maintain
platform specific binaries. I rather spend my time in debugging and
implementing additional file formats.

Right now, the project is in an alpha stage and you have to spend some time
to learn the toolchain to create executables on your own.

Regards,

Andreas
