### ISSUE TITLE
Compile will fail when disable matlab

### ISSUE THREAD

**Issue by chenzilin** [aheit/cantools#10]
**My Configs:**
libtoolize
autoreconf -f -i
./configure --prefix=${PREFIX} --disable-matlab --enable-shared=yes --enable-static=no
make -j12
make install

**My Error:**
/usr/bin/ld: src/cantomat/cantomat-matwrite.o: in function `matWrite':
/home/chenzilin/Documents/Github/cantools/src/cantomat/matwrite.c:42: undefined reference to `Mat_CreateVer'
/usr/bin/ld: /home/chenzilin/Documents/Github/cantools/src/cantomat/matwrite.c:81: undefined reference to `Mat_VarCreate'
/usr/bin/ld: /home/chenzilin/Documents/Github/cantools/src/cantomat/matwrite.c:83: undefined reference to `Mat_VarWrite'
/usr/bin/ld: /home/chenzilin/Documents/Github/cantools/src/cantomat/matwrite.c:84: undefined reference to `Mat_VarFree'
/usr/bin/ld: /home/chenzilin/Documents/Github/cantools/src/cantomat/matwrite.c:93: undefined reference to `Mat_Close'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1050: cantomat] Error 1
make[2]: Leaving directory '/home/chenzilin/Documents/Github/cantools'
make[1]: *** [Makefile:1562: all-recursive] Error 1
make[1]: Leaving directory '/home/chenzilin/Documents/Github/cantools'
make: *** [Makefile:757: all] Error 2

**My resolve method**
diff --git a/Makefile.am b/Makefile.am
index 2ad8b1a..714ac57 100755
--- a/Makefile.am
+++ b/Makefile.am
@@ -31,9 +31,9 @@ YACC=@YACC@
 lib_LTLIBRARIES = libcandbc.la libcanasc.la libcanmdf.la libcanvsb.la \
                  libcanclg.la libcanblf.la libmatfile.la
 
-bin_PROGRAMS   = dbccopy dbcls cantomat
+bin_PROGRAMS   = dbccopy dbcls
 if MATLAB
-bin_PROGRAMS   += mdftomat matdump
+bin_PROGRAMS   += mdftomat matdump cantomat
 endif
 
 #
@@ -208,6 +208,7 @@ MAINTAINERCLEANFILES = \
 
 src/libcandbc/parser.h src/libcandbc/parser.c: src/libcandbc/parser.y
 
+if MATLAB
 install-exec-hook:
        cd $(DESTDIR)$(bindir) && \
                $(LN_S) cantomat$(EXEEXT) asctomat$(EXEEXT)
@@ -217,3 +218,4 @@ install-exec-hook:
                $(LN_S) cantomat$(EXEEXT) vsbtomat$(EXEEXT)
        cd $(DESTDIR)$(bindir) && \
                $(LN_S) cantomat$(EXEEXT) clgtomat$(EXEEXT)
+endif

**Comment by aheit** [comment]
The issue should be fixed with version 0.30. Thanks for the report.
