### ISSUE TITLE
cantomat 0.31 produces only header in .mat file

### ISSUE THREAD

**Issue by skrtre** [aheit/cantools#11]
I build cantools on Ubuntu 20.04. No errors in makes but when tried cantomat the output was "MATLAB 5.0 MAT-file, Platform: x86_64-pc-linux-gnu, Created by: libmatio v1.5.17 on Wed ... 'NUL' 'NUL''SOH'IM". Nothing else. I have used cantomat about five year ago but no ideas what was the Linux distro then. Any ideas what is wrong with my build? Thanks.

**Comment by aheit** [comment]
Hello,

thanks for the report. Let me try to understand the issue better. What type
of input file are you trying to convert? Would you be able to send me those
files?

Regards,
Andreas

skrtre ***@***.***> schrieb am Mi., 3. Nov. 2021, 20:22:

**Comment by skrtre** [comment]
Hello Andreas,

The simple example is attached. The used command was
> cantomat -d simple.dbc -a sample.asc -m sample.mat --verbose
Parsing DBC file simple.dbc
Parsing input file sample.asc
Writing MAT file sample.mat

[Test.zip](https://github.com/aheit/cantools/files/7473281/Test.zip)

Regards,
Seppo

**Comment by aheit** [comment]
Hello Seppo,

the asc file has logged the messages on bus 1, so you need to associate the
dbc file with this bus on the command line:

cantomat -b 1 -d simple.dbc -a sample.asc -m sample.mat --verbose

I hope this solves the problem.

Regards,
Andreas


skrtre ***@***.***> schrieb am Do., 4. Nov. 2021, 09:28:

**Comment by skrtre** [comment]
Hello Andreas,

You are right. I assumed that the default bus is 1 and -b is not needed. After that the created mat file was perfect.

Thanks,
Seppo
