### ISSUE TITLE
missing head files when make install

### ISSUE THREAD

**Issue by liurunjieuk** [aheit/cantools#13]
1、missing head files when make install
2、rjsc@rjsc-virtual-machine:~/dw/cantools-all/cantools/build$ sudo make install
```
[  4%] Built target matfile
[ 20%] Built target canmdf
[ 25%] Built target mdftomat
[ 29%] Built target matdump
[ 33%] Built target canclg
[ 39%] Built target hashtable
[ 43%] Built target canvsb
[ 60%] Built target candbc
[ 64%] Built target canasc
[ 75%] Built target canblf
[ 91%] Built target cantomat
[ 95%] Built target dbccopy
[100%] Built target dbcls
Install the project...
-- Install configuration: ""
-- Up-to-date: /usr/local/bin/dbccopy
-- Up-to-date: /usr/local/bin/dbcls
-- Up-to-date: /usr/local/bin/cantomat
-- Up-to-date: /usr/local/bin/mdftomat
-- Up-to-date: /usr/local/bin/matdump
```

**Comment by aheit** [comment]
> 1、missing head files when make install
> 2、rjsc@rjsc-virtual-machine:~/dw/cantools-all/cantools/build$ sudo make install
> [  4%] Built target matfile
> [ 20%] Built target canmdf
> [ 25%] Built target mdftomat
> [ 29%] Built target matdump
> [ 33%] Built target canclg
> [ 39%] Built target hashtable
> [ 43%] Built target canvsb
> [ 60%] Built target candbc
> [ 64%] Built target canasc
> [ 75%] Built target canblf
> [ 91%] Built target cantomat
> [ 95%] Built target dbccopy
> [100%] Built target dbcls
> Install the project...
> -- Install configuration: ""
> -- Up-to-date: /usr/local/bin/dbccopy
> -- Up-to-date: /usr/local/bin/dbcls
> -- Up-to-date: /usr/local/bin/cantomat
> -- Up-to-date: /usr/local/bin/mdftomat
> -- Up-to-date: /usr/local/bin/matdump

Hi,

thanks for your report. I'm going to check  it in the next days.

However, your log indicates no issues. Which file are you missing?

Regards,
Andreas

**Comment by liurunjieuk** [comment]
@aheit hi friend,thanks you for you early reply.the missing files:
 ```
 libcanasc
libcanblf
libcanclg
libcandbc
libcanmdf
libcanvsb
libmatfile
```
and so on,i can't find
``` 
*.a/*.so/*.h
```
 when i exec 'make install',i only find some bin files
 ```
canvsb
candbc
canasc
canblf
cantomat

 ```

**Comment by aheit** [comment]
I just tried to reproduce with a fresh checkout. The build is completing and make install is without errors:

aheit$ mkdir testcantools
aheit$ cd testcantools
aheit$ git clone https://github.com/aheit/cantools cantools-code
Cloning into 'cantools-code'...
remote: Enumerating objects: 1219, done.
remote: Counting objects: 100% (194/194), done.
remote: Compressing objects: 100% (120/120), done.
remote: Total 1219 (delta 110), reused 125 (delta 72), pack-reused 1025
Receiving objects: 100% (1219/1219), 1.91 MiB | 6.66 MiB/s, done.
Resolving deltas: 100% (842/842), done.
aheit$ cd cantools-code/
aheit$ mkdir build
aheit$ cd build/
aheit$ cmake ..
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for 4 include files stdlib.h, ..., float.h
-- Looking for 4 include files stdlib.h, ..., float.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Dmalloc disabled
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned long long int
-- Check size of unsigned long long int - done
Byte order: LITTLE_ENDIAN
-- Performing Test HAVE_ARITHMETIC_RSHIFT
-- Performing Test HAVE_ARITHMETIC_RSHIFT - Success
-- Looking for LINE_MAX
-- Looking for LINE_MAX - found
-- Found FLEX: /usr/bin/flex.exe (found version "2.6.4")
-- Found BISON: /usr/bin/bison.exe (found version "3.8.2")
-- Found ZLIB: /usr/lib/libz.dll.a (found version "1.3.1")
-- Found Matio
-- Found HDF5: /usr/lib/libhdf5.dll.a;/usr/lib/libz.dll.a;/usr/lib/libdl.a;/usr/lib/libm.a (found version "1.10.5")
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/testcantools/cantools-code/build
aheit$ make
[  2%] [BISON][PARSER] Building parser with bison 3.8.2
[  4%] [FLEX][LEXER] Building scanner with flex 2.6.4
[  6%] Building C object CMakeFiles/candbc.dir/src/libcandbc/dbcmodel.c.o
[  8%] Building C object CMakeFiles/candbc.dir/src/libcandbc/dbcreader.c.o
[ 10%] Building C object CMakeFiles/candbc.dir/src/libcandbc/dbcwriter.c.o
[ 12%] Building C object CMakeFiles/candbc.dir/dbclexer.c.o
/tmp/testcantools/cantools-code/build/dbclexer.c:1674:16: warning: ‘input’ defined but not used [-Wunused-function]
 1674 | #else
      |                ^
/tmp/testcantools/cantools-code/build/dbclexer.c:1627:17: warning: ‘yyunput’ defined but not used [-Wunused-function]
 1627 |
      |                 ^
[ 14%] Building C object CMakeFiles/candbc.dir/dbcparser.c.o
[ 16%] Linking C static library libcandbc.a
[ 16%] Built target candbc
[ 18%] Building C object CMakeFiles/canasc.dir/src/libcanasc/ascreader.c.o
/tmp/testcantools/cantools-code/src/libcanasc/ascreader.c: In function ‘ascReader_processFile’:
/tmp/testcantools/cantools-code/src/libcanasc/ascreader.c:84:15: warning: variable ‘d’ set but not used [-Wunused-but-set-variable]
   84 |       char   *d;
      |               ^
[ 20%] Linking C static library libcanasc.a
[ 20%] Built target canasc
[ 22%] Building C object CMakeFiles/canblf.dir/src/libcanblf/blfreader.c.o
[ 25%] Building C object CMakeFiles/canblf.dir/src/libcanblf/blfparser.c.o
[ 27%] Building C object CMakeFiles/canblf.dir/src/libcanblf/blfstream.c.o
[ 29%] Building C object CMakeFiles/canblf.dir/src/libcanblf/blfapi.c.o
[ 31%] Linking C static library libcanblf.a
[ 31%] Built target canblf
[ 33%] Building C object CMakeFiles/canclg.dir/src/libcanclg/clgreader.c.o
[ 35%] Linking C static library libcanclg.a
[ 35%] Built target canclg
[ 37%] Building C object CMakeFiles/canmdf.dir/src/libcanmdf/mdfcg.c.o
[ 39%] Building C object CMakeFiles/canmdf.dir/src/libcanmdf/mdfcn.c.o
/tmp/testcantools/cantools-code/src/libcanmdf/mdfcn.c: In function ‘mdfProcessChannelsSorted’:
/tmp/testcantools/cantools-code/src/libcanmdf/mdfcn.c:93:10: warning: variable ‘dims’ set but not used [-Wunused-but-set-variable]
   93 |   size_t dims[2];
      |          ^~~~
/tmp/testcantools/cantools-code/src/libcanmdf/mdfcn.c:89:28: warning: variable ‘second_record_id’ set but not used [-Wunused-but-set-variable]
   89 |   uint8_t first_record_id, second_record_id;
      |                            ^~~~~~~~~~~~~~~~
/tmp/testcantools/cantools-code/src/libcanmdf/mdfcn.c:89:11: warning: variable ‘first_record_id’ set but not used [-Wunused-but-set-variable]
   89 |   uint8_t first_record_id, second_record_id;
      |           ^~~~~~~~~~~~~~~
[ 41%] Building C object CMakeFiles/canmdf.dir/src/libcanmdf/mdfdg.c.o
[ 43%] Building C object CMakeFiles/canmdf.dir/src/libcanmdf/mdffile.c.o
[ 45%] Building C object CMakeFiles/canmdf.dir/src/libcanmdf/mdffilter.c.o
[ 47%] Building C object CMakeFiles/canmdf.dir/src/libcanmdf/mdfmodel.c.o
[ 50%] Building C object CMakeFiles/canmdf.dir/src/libcanmdf/mdfsg.c.o
[ 52%] Linking C static library libcanmdf.a
[ 52%] Built target canmdf
[ 54%] Building C object CMakeFiles/matfile.dir/src/libmatfile/matfile.c.o
[ 56%] Linking C static library libmatfile.a
[ 56%] Built target matfile
[ 58%] Building C object CMakeFiles/canvsb.dir/src/libcanvsb/vsbreader.c.o
[ 60%] Linking C static library libcanvsb.a
[ 60%] Built target canvsb
[ 62%] Building C object CMakeFiles/hashtable.dir/src/hashtable/hashtable.c.o
[ 64%] Building C object CMakeFiles/hashtable.dir/src/hashtable/hashtable_itr.c.o
[ 66%] Linking C static library libhashtable.a
[ 66%] Built target hashtable
[ 68%] Building C object CMakeFiles/dbccopy.dir/src/dbccopy/dbccopy.c.o
[ 70%] Linking C executable dbccopy.exe
[ 70%] Built target dbccopy
[ 72%] Building C object CMakeFiles/dbcls.dir/src/dbcls/dbcls.c.o
[ 75%] Linking C executable dbcls.exe
[ 75%] Built target dbcls
[ 77%] Building C object CMakeFiles/cantomat.dir/src/cantomat/cantomat.c.o
[ 79%] Building C object CMakeFiles/cantomat.dir/src/cantomat/messagedecoder.c.o
[ 81%] Building C object CMakeFiles/cantomat.dir/src/cantomat/busassignment.c.o
[ 83%] Building C object CMakeFiles/cantomat.dir/src/cantomat/matwrite.c.o
[ 85%] Building C object CMakeFiles/cantomat.dir/src/cantomat/messagehash.c.o
[ 87%] Building C object CMakeFiles/cantomat.dir/src/cantomat/measurement.c.o
/tmp/testcantools/cantools-code/src/cantomat/measurement.c:71:13: warning: ‘signalProc_print’ defined but not used [-Wunused-function]
   71 | static void signalProc_print(
      |             ^~~~~~~~~~~~~~~~
[ 89%] Building C object CMakeFiles/cantomat.dir/src/cantomat/signalformat.c.o
[ 91%] Linking C executable cantomat.exe
[ 91%] Built target cantomat
[ 93%] Building C object CMakeFiles/mdftomat.dir/src/mdftomat/mdftomat.c.o
[ 95%] Linking C executable mdftomat.exe
[ 95%] Built target mdftomat
[ 97%] Building C object CMakeFiles/matdump.dir/src/matdump/matdump.c.o
[100%] Linking C executable matdump.exe
[100%] Built target matdump
aheit$ make install
[ 16%] Built target candbc
[ 20%] Built target canasc
[ 31%] Built target canblf
[ 35%] Built target canclg
[ 52%] Built target canmdf
[ 56%] Built target matfile
[ 60%] Built target canvsb
[ 66%] Built target hashtable
[ 70%] Built target dbccopy
[ 75%] Built target dbcls
[ 91%] Built target cantomat
[ 95%] Built target mdftomat
[100%] Built target matdump
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/bin/dbccopy.exe
-- Installing: /usr/local/bin/dbcls.exe
-- Installing: /usr/local/bin/cantomat.exe
-- Installing: /usr/local/bin/mdftomat.exe
-- Installing: /usr/local/bin/matdump.exe
aheit$

The intermediate archive, header, and object files you are looking for are created below your build/ folder during make. 

I hope this helps. 

Regards,
Andreas

**Comment by aheit** [comment]
location of files has been pointed out, closing the issue
