### ISSUE TITLE
Convert ASC files to MDF

### ISSUE THREAD

**Issue by Mark584** [aheit/cantools#5]
Hello Andreas,

is it possible to use your tool to convert asc files to mdf?
I successfully converted asc files to mat with your tool, but I couldn't figure out if it's also possible to convert them to mdf.

Kind regards
Mark

**Comment by aheit** [comment]
Mark,

quick answer: yes. If you specify the input format as ASC with a command
line switch (-a or --asc) for the cantomdf tool, it should read the file
and convert it. You also need to specify a dbc file. I'm currently
travelling and don't have access to my computer, so I can't give you a
working command line.

If you are still in trouble, write me again with your best guess, I'll
correct it later this weekend.

Regards,
Andreas



Mark584 <notifications@github.com> schrieb am Fr., 6. Apr. 2018, 11:49:

**Comment by Mark584** [comment]
Is there a cantomdf tool? In my compiled folder I can only find a cantomat tool and a mdftomat tool. Should there also be a cantomdf tool? (I compiled the source code with cygwin and gcc)

To convert a ASC to MAT I used the following command:
cantomat -a 'ascfile.asc' -d 'dbcfile.dbc' -m 'output.mat'

In the libs folder I found a "libcanmdf.a" file - but I unfortunately don't know how to use this to convert my files

**Comment by aheit** [comment]
Hello Mark,

I'm sorry, I misread your initial mail. No, there is no tool in my package
to convert anything to .mdf.

The reason is simply that I didn't need such a converter yet, as my main
application is to import existing log files to MATLAB.

Sorry again for the inconvenience.

Regards,
Andreas


2018-04-09 14:31 GMT+02:00 Mark584 <notifications@github.com>:

**Comment by sashaasf** [comment]
> Is there a cantomdf tool? In my compiled folder I can only find a cantomat tool and a mdftomat tool. Should there also be a cantomdf tool? (I compiled the source code with cygwin and gcc)
> 
> To convert a ASC to MAT I used the following command:
> cantomat -a 'ascfile.asc' -d 'dbcfile.dbc' -m 'output.mat'
> 
> In the libs folder I found a "libcanmdf.a" file - but I unfortunately don't know how to use this to convert my files

Hi 

I'm looking to a solution for the same problem (asc->mdf) , even without dbc parsing
Did you find any tools/solution for this

Thank you

**Comment by aheit** [comment]
Hello Sashaaf,

currently cantools do not provide a conversion to mdf. I focused on conversion to MAT.

I did not research if there are other converters for the job.

Sorry and regards,
Andreas

**Comment by roboticvedant** [comment]
@sashaasf  you can use peak converter or something to convert the ASC to MDF i believe,
