### ISSUE TITLE
Consistency with SourceForge SVN ?!

### ISSUE THREAD

**Issue by s-hemer** [aheit/cantools#6]
When comparing your different code bases, I really get confused. Neither version number (0.24 vs 0.10) nor last checkin dates (2017-08-21 vs 2017-09-13) give a clue how the [SForge SVN](https://sourceforge.net/p/cantools) is related to the present Git. Ok the version tags here seem not to be maintained (0.10 is from 2014) as in the SVN but the last contribution here has not made it to the SVN yet. So can I assume the Git master branch is the newest?

Regards

Steffen

**Comment by aheit** [comment]
Hallo Steffen,

 

Ich hatte versucht, die Stände auf Github und Sourceforge synchron zu halten, aber anscheinend hat es nicht geklappt. Ich denke, dass ich als nächsten Schritt das Repository auf Sourceforge deaktiviere und dort auf github verweise.

 

Leider habe ich im Moment wenig Zeit, um die Versionsnummern und mögliche andere Unterschiede zu bereinigen. Mein Rat wäre, das neueste Tar-File von Sourceforge zu laden.

 

Viele Grüße und sorry für die Konfusion.

 

Gruß,

Andreas

 

 

 

Von: s-hemer <notifications@github.com> 
Gesendet: Donnerstag, 10. Mai 2018 13:23
An: aheit/cantools <cantools@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [aheit/cantools] Consistency with SourceForge SVN ?! (#6)

 

When comparing your different code bases, I really get confused. Neither version number (0.24 vs 0.10) nor last checkin dates (2017-08-21 vs 2017-09-13) give a clue how the SForge SVN <https://sourceforge.net/p/cantools>  is related to the present Git. Ok the version tags here seem not to be maintained (0.10 is from 2014) as in the SVN but the last contribution here has not made it to the SVN yet. So can I assume the Git master branch is the newest?

Regards

Steffen
