### ISSUE TITLE
How to build documentation

### ISSUE THREAD

**Issue by dangri94** [aheit/cantools#8]
Hello Andreas,

When I'm building cantools under Ubuntu 18.04, I'm not getting any documentation files... 

commands I used:

- _cd cantools_

- _libtoolize_

- _autoreconf -f -i_

- _./configure --disable-matlab --enable-shared=yes --enable-static=no_

- _make_

- _sudo make install_

Specifiying the docdir FLAG in ./configure has also no effect.

is there a special flag that needs to be set?

Kind Regards,
Daniel

**Comment by aheit** [comment]
Hello Daniel,

I'm sorry, there's no documentation currently apart from the README and the built-in usage information (use the --help flag of the binaries).

Regards,
Andreas
