### ISSUE TITLE
"./configure" complains about CHECK

### ISSUE THREAD

**Issue by nonujigu** [aheit/cantools#9]
While trying to install cantools on a CentOS8 machine, the configure script ends with the following lines:

********************************************************************************************************************
checking for CHECK... no
configure: error: Package requirements (check >= 0.9.0) were not met:

Package 'check', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables CHECK_CFLAGS
and CHECK_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

********************************************************************************************************************

With these errors, Makefile has not been created.
The package "check" has been installed in version 0.12.0 though:

********************************************************************************************************************

Installierte Pakete
Name         : check
Version      : 0.12.0
Release      : 2.el8
Architecture : x86_64
Size         : 150 k
Quelle       : check-0.12.0-2.el8.src.rpm
Repository   : @System
Aus Paketque : AppStream
Summary      : A unit test framework for C
URL          : http://libcheck.github.io/check/
Lizenz       : LGPLv2+
Description  : Check is a unit test framework for C. It features a simple interface for
             : defining unit tests, putting little in the way of the developer. Tests
             : are run in a separate address space, so Check can catch both assertion
             : failures and code errors that cause segmentation faults or other signals.
             : The output from unit tests can be used within source code editors and IDEs.

********************************************************************************************************************

**Comment by aheit** [comment]
Hello nonujigu,

thanks for the report, I'll try to reproduce and fix it.

Regards,
Andreas

**Comment by aheit** [comment]
Hello nonujigu,

I think you may have installed a wrong type of the check package. You installed "check-0.12.0-2.el8.src.rpm" which is a source package. You did not actually install check but rather its source code.

You can either compile and install check from this installed source rpm, or you can download the binary package, which should be named "check-0.12.0-2.el8.x86_64.rpm".

Can you confirm my assumption?

Regards,
Andreas

**Comment by nonujigu** [comment]
Hello Andreas,

actually the package "check.x86_64" has been installed via dnf package manager. This should be a compiled package. Just when I enter "dnf info check" on the cli the output is also showing its corresponding source package.

"dnf list installed | grep check" on the cli has the following output:

check.x86_64                                       0.12.0-2.el8                                   @AppStream
checkpolicy.x86_64                                 2.9-1.el8                                      @anaconda
fipscheck.x86_64                                   1.5.0-4.el8                                    @anaconda
fipscheck-lib.x86_64                               1.5.0-4.el8                                    @anaconda

Best regards

**Comment by aheit** [comment]
Hello nonujigu,

I tried to reproduce the issue with a docker installation of CentOS and received the same error message.

It seems that one needs to install check-devel as well. This package provides the file check.pc which is needed by pkgconf.

Please check if installation of check-devel resolves the issue.

Regards,
Andreas

**Comment by aheit** [comment]
README updated on prerequisites (check-devel) in version 0.29.
